import = [
    "/home/michell/.config/alacritty/color.toml",
]

[env]
TERM = "xterm-256color"

[font]
size = 11.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 1

[keyboard]
bindings = [
    { action = "Paste", key = "V", mods = "Control|Shift" },
    { action = "Copy", key = "C", mods = "Control|Shift" },
    { action = "PasteSelection", key = "Insert", mods = "Shift" },
    { action = "ResetFontSize", key = "Key0", mods = "Control" },
    { action = "IncreaseFontSize", key = "Equals", mods = "Control" },
    { action = "IncreaseFontSize", key = "Plus", mods = "Control" },
    { action = "DecreaseFontSize", key = "Minus", mods = "Control" },
    { action = "ToggleFullscreen", key = "F11", mods = "None" },
    { action = "Paste", key = "Paste", mods = "None" },
    { action = "Copy", key = "Copy", mods = "None" },
    { action = "ClearLogNotice", key = "L", mods = "Control" },
    { chars = "\f", key = "L", mods = "Control" },
    { action = "ScrollPageUp", key = "PageUp", mode = "~Alt", mods = "None" },
    { action = "ScrollPageDown", key = "PageDown", mode = "~Alt", mods = "None" },
    { action = "ScrollToTop", key = "Home", mode = "~Alt", mods = "Shift" },
    { action = "ScrollToBottom", key = "End", mode = "~Alt", mods = "Shift" },
]

[scrolling]
history = 5000

[window]
dynamic_padding = false
opacity = 0.98
blur = true
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 2
y = 1
